name: test-dart

permissions: {}

on:
  push:
    branches:
      - main
      - renovate/**
    paths:
      - dart/**
      - testdata/**
      - Makefile
      - .github/**
  pull_request:
    branches:
      - main
    paths:
      - dart/**
      - testdata/**
      - Makefile
      - .github/**

jobs:
  test-dart:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        dart: ["3.7.0", "3.12.0"]
        include:
          - os: windows-latest
            dart: "3.12.0"
          - os: macos-latest
            dart: "3.12.0"

    defaults:
      run:
        working-directory: dart

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: ${{ matrix.dart }}

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Install coverage tools
        run: dart pub global activate coverage 1.15.0

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze

      - name: Test with 100% coverage
        run: dart pub global run coverage:test_with_coverage --fail-under 100

      - name: Verify publishable package
        run: dart pub publish --dry-run

  coverage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    defaults:
      run:
        working-directory: dart

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: dart-lang/setup-dart@7654d458321ee25acccccfdb86cd48bd95768ff1 # v1.8.0
        with:
          sdk: "3.12.0"

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Collect coverage
        run: dart test --coverage=coverage

      - name: Format coverage
        run: >-
          dart run coverage:format_coverage
          --packages=.dart_tool/package_config.json
          --report-on=lib
          --ignore-files="lib/src/generated/**"
          --in=coverage
          --out=coverage/lcov.info
          --lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          disable_search: true
          fail_ci_if_error: true
          files: dart/coverage/lcov.info
          flags: dart
          use_oidc: true
